version: '3.7'

services:

  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    depends_on:
      - app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:r


  app:
    image: app
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .docker.env
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.app.schedule: "@every 59s"
      ofelia.job-exec.app.command: "bash scraper.sh"
