"""first commit

Revision ID: 29b841b1f3f5
Revises: 
Create Date: 2023-04-09 18:23:57.545158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b841b1f3f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influenza_gtrends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('cough', sa.Integer(), nullable=True),
    sa.Column('flu', sa.Integer(), nullable=True),
    sa.Column('tamiflu', sa.Integer(), nullable=True),
    sa.Column('sore_throat', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('state_code', sa.String(length=200), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'level', 'state', 'state_code')
    )
    op.create_table('influenza_ilinet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_type', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('perc_weight_ili', sa.Float(), nullable=True),
    sa.Column('perc_unweight_ili', sa.Float(), nullable=True),
    sa.Column('age_0_4', sa.Integer(), nullable=True),
    sa.Column('age_25_49', sa.Integer(), nullable=True),
    sa.Column('age_25_64', sa.Integer(), nullable=True),
    sa.Column('age_5_24', sa.Integer(), nullable=True),
    sa.Column('age_50_64', sa.Integer(), nullable=True),
    sa.Column('age_65', sa.Integer(), nullable=True),
    sa.Column('ilitotal', sa.Integer(), nullable=True),
    sa.Column('num_providers', sa.Integer(), nullable=True),
    sa.Column('total_patients', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_type', 'region', 'year', 'week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influenza_ilinet')
    op.drop_table('influenza_gtrends')
    # ### end Alembic commands ###
