"""unique constraints

Revision ID: 3406be38504b
Revises: 29b841b1f3f5
Create Date: 2023-04-09 20:08:49.244428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3406be38504b'
down_revision = '29b841b1f3f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('influenza_gtrends_date_level_state_state_code_key', 'influenza_gtrends', type_='unique')
    op.create_unique_constraint('unique_gtrends', 'influenza_gtrends', ['date', 'level', 'state', 'state_code'])
    op.drop_constraint('influenza_ilinet_region_type_region_year_week_key', 'influenza_ilinet', type_='unique')
    op.create_unique_constraint('unique_ilinet', 'influenza_ilinet', ['region_type', 'region', 'year', 'week'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_ilinet', 'influenza_ilinet', type_='unique')
    op.create_unique_constraint('influenza_ilinet_region_type_region_year_week_key', 'influenza_ilinet', ['region_type', 'region', 'year', 'week'])
    op.drop_constraint('unique_gtrends', 'influenza_gtrends', type_='unique')
    op.create_unique_constraint('influenza_gtrends_date_level_state_state_code_key', 'influenza_gtrends', ['date', 'level', 'state', 'state_code'])
    # ### end Alembic commands ###
